version: "3.9"

services:
    mongo:
        image: "mongo"
        environment:
            MONGO_INITDB_DATABASE: hangmandb
        ports:
            - "27017:27017"
        volumes:
            - db-data:/data/db
            - ./initdb/initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro #ro = read only
        container_name: hangmandb

    traefik:
        image: "traefik:v2.4"
        container_name: "traefik"
        command:
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        ports:
            - "80:80"
        volumes:
            - "./traefik.yml:/etc/traefik/traefik.yml"
            - "./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
    db-data:
