# Start with:
# docker-compose -f docker-compose.production.yml up

version: "3.9"

services:
    express:
        build: .
        networks:
            - internal
        deploy:
            mode: replicated
            replicas: 2

    mongo:
        image: "mongo"
        environment:
            MONGO_INITDB_DATABASE: hangmandb
        ports:
            - "27017:27017"
        volumes:
            - db-data:/data/db
            - ./services/repository/initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro #ro = read only
        container_name: hangmandb
        networks:
            - internal

    traefik:
        image: "traefik:v2.4"
        container_name: "traefik"
        command:
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "./traefik.yml:/etc/traefik/traefik.yml"
            - "./traefik_dynamic_production.yml:/etc/traefik/traefik_dynamic.yml"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        networks:
            - internal
            - external
        depends_on:
            - express

volumes:
    db-data:

networks:
    external:
    internal:
        internal: true