http:
    routers:
        my-router:
            rule: "PathPrefix(`/`)"
            entryPoints:
                - "web"
            service: "hangman-service"
            
    services:
        hangman-service:
            loadBalancer:
                healthCheck:
                    path: /login
                    interval: "10s"
                    timeout: "3s"
                servers:
                    - url: "http://host.docker.internal:3000/"