http:
  routers:
    my-router:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - "web"
      service: "hangman-service"

  services:
    hangman-service:
      loadBalancer:
        healthCheck:
          path: /login
          interval: "10s"
          timeout: "3s"
        servers:
          - url: "http://hangman_express_1:3000"
          - url: "http://hangman_express_2:3000"