http:
    routers:
        my-router:
            rule: "PathPrefix(`/`)"
            entryPoints:
                - "web"
            service: "my-service"
            
    services:
        my-service:
            loadBalancer:
                servers:
                    - url: "http://host.docker.internal:3000/"
