http:
    routers:
        my-router:
            rule: "PathPrefix(`/`)"
            entryPoints:
                - "web"
            service: "my-service"
            
    services:
        my-service:
            loadBalancer:
                healthCheck:
                    path: /
                    interval: "10s"
                    timeout: "3s"
                servers:
                    - url: "http://host.docker.internal:3000/"
                    - url: "http://host.docker.internal:3001/"
